import { Inter } from "next/font/google";
import "./globals.css";
import ApProvider from "@/components/ApProvider";
import Header from "@/components/Header";
import ReduxProvider from "./redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApProvider>
          <ReduxProvider>
            {/* <Header /> */}
            {children}
          </ReduxProvider>
        </ApProvider>
      </body>
    </html>
  );
}
